let fs = require('fs');
let Observable = require('rxjs').Observable;
let combineLatest = require('rxjs').combineLatest;

let exec = require('child_process').exec;

const revision = new Observable(s => {
    exec('git rev-parse --short HEAD',
        function (error, stdout, stderr) {
            if (error !== null) {
                console.log('git error: ' + error + stderr);
            }
            s.next(stdout.toString().trim());
            s.complete();
        });
});

const branch = new Observable(s => {
    exec('git rev-parse --abbrev-ref HEAD',
        function (error, stdout, stderr) {
            if (error !== null) {
                console.log('git error: ' + error + stderr);
            }
            s.next(stdout.toString().trim());
            s.complete();
        });
});

combineLatest(revision, branch)
  .subscribe(([revision, branch]) => {
      console.log(`version: '${process.env.npm_package_version}', revision: '${revision}', branch: '${branch}'`);

      const content = '// this file is automatically generated by git.version.js script\n' +
          `export const versions = {version: '${process.env.npm_package_version}', revision: '${revision}', branch: '${branch}'};`;

      fs.writeFileSync(
          'src/versions.js',
          content,
          {encoding: 'utf8'}
      );
  });
